version: '3.1'
services:

  # Authorization SERVER
  authorizatioin_server:
    container_name: authorization-server
    environment:
      - 'JAVA_TOOL_OPTIONS=-Djava.awt.headless=true -Dfile.encoding=UTF-8 -XX:PermSize=512m -Xmx2048M -Xms1024M -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=20
      -XX:ConcGCThreads=5 -XX:InitiatingHeapOccupancyPercent=70'
    image: authorization-server:0.0.1
    volumes:
      - ~/.m2:/root/.m2
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/environment:/etc/environment:ro
      - ~/logs:/root/logs
    ports:
      - "19999:8080"
      # BackOffice-API
    backoffice_api:
        container_name: backoffice-api
        environment:
          - 'JAVA_TOOL_OPTIONS=-Djava.awt.headless=true -Dfile.encoding=UTF-8 -XX:PermSize=512m -Xmx2048M -Xms1024M -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=20
          -XX:ConcGCThreads=5 -XX:InitiatingHeapOccupancyPercent=70'
        image: backoffice-api:0.0.1
        volumes:
          - ~/.m2:/root/.m2
          - /etc/timezone:/etc/timezone:ro
          - /etc/localtime:/etc/localtime:ro
          - /etc/environment:/etc/environment:ro
          - ~/logs:/root/logs
        ports:
          - "18888:8080"